version: 1.0
Resources:
  -TargetService:
    Type: AWS::ECS::Service
    Properties:
      TaskDefinition: "arn:aws:ecs:us-east-1:610018615348:task-definition/malhar-pms:1"
      LoadBalancerInfo:
        ContainerName: "malhar-pms"
        ContainerPort: "8082"
      PlatformVersion: "Latest"
